"""매일 아침 발송용 미국 일상 대화 목록. 하루에 하나씩 순환 재생된다.

각 에피소드: id, title(영문), topic(한글 부제), dialogue(리스트).
dialogue의 각 줄: (화자, 목소리, 영어 대사, 한글 해석)
"""

MALE_VOICE = "en-US-GuyNeural"
FEMALE_VOICE = "en-US-AriaNeural"
M, F = MALE_VOICE, FEMALE_VOICE

EPISODES = [
    {
        "id": "day01_hike",
        "title": "Mike & Sarah's Saturday Hike",
        "topic": "오랜만에 만난 친구와 주말 하이킹 계획 잡기",
        "dialogue": [
            ("Mike", M, "Hey Sarah! Long time no see. How's it going?", "안녕 사라! 오랜만이다. 잘 지냈어?"),
            ("Sarah", F, "Oh my gosh, hi Mike! I'm doing okay, just super busy lately. How about you?", "어머, 안녕 마이크! 나는 괜찮아, 요즘 그냥 엄청 바빠. 너는?"),
            ("Mike", M, "Same here, honestly. Work's been crazy this week.", "나도 그래, 솔직히. 이번 주에 일이 정신없었어."),
            ("Sarah", F, "Yeah? What's going on?", "그래? 무슨 일 있어?"),
            ("Mike", M, "We're launching a new project, so I've been staying late almost every night.", "새 프로젝트를 시작해서 거의 매일 밤 늦게까지 남아 있었어."),
            ("Sarah", F, "Ugh, that sounds exhausting. Are you getting any sleep at all?", "아이고, 진짜 힘들겠다. 잠은 좀 자?"),
            ("Mike", M, "Barely. I've basically been living on coffee for the past few days.", "거의 못 자. 요 며칠은 그냥 커피로 버티고 있어."),
            ("Sarah", F, "I feel you. I did the same thing last month when we had that big deadline.", "무슨 말인지 알아. 지난달에 큰 마감 있을 때 나도 그랬거든."),
            ("Mike", M, "Oh right, how did that turn out?", "아 맞다, 그거 어떻게 됐어?"),
            ("Sarah", F, "It actually went pretty well in the end. We were all just running on fumes by Friday, though.", "결국엔 꽤 잘 됐어. 근데 금요일쯤엔 다들 완전히 지쳐 있었지."),
            ("Mike", M, "Ha, I bet. So, what have you been up to besides work?", "하, 그럴 것 같아. 그래서 일 말고는 요즘 뭐 하고 지내?"),
            ("Sarah", F, "Honestly, not much. I've been trying to get back into cooking, actually.", "솔직히 별거 없어. 사실 요리를 다시 시작해보려고 하고 있어."),
            ("Mike", M, "Oh nice, what have you made?", "오 좋다, 뭐 만들었는데?"),
            ("Sarah", F, "Last weekend I tried this new pasta recipe. It was a total disaster, by the way.", "지난 주말에 새 파스타 레시피를 시도해봤어. 근데 완전 망했어."),
            ("Mike", M, "Ha, what happened?", "하하, 무슨 일이었는데?"),
            ("Sarah", F, "I completely burned the garlic and the whole kitchen smelled like smoke for hours.", "마늘을 완전히 태워서 부엌 전체가 몇 시간 동안 탄내로 가득했어."),
            ("Mike", M, "Oh no. Did you at least end up eating it?", "이런. 그래도 결국 먹긴 먹었어?"),
            ("Sarah", F, "Yeah, I just picked out the burnt bits and pretended it was intentional.", "응, 그냥 탄 부분만 골라내고 일부러 그런 척했어."),
            ("Mike", M, "That's the spirit. So are you doing anything fun this weekend?", "그런 자세 좋지. 그래서 이번 주말엔 재밌는 거 해?"),
            ("Sarah", F, "Actually, yeah. A few of us are planning to go hiking on Saturday if the weather holds up.", "어, 사실 있어. 날씨만 괜찮으면 토요일에 몇 명이서 등산 가려고."),
            ("Mike", M, "Oh, that sounds great. Where are you guys headed?", "오, 좋겠다. 어디로 가는데?"),
            ("Sarah", F, "There's this trail about an hour outside the city. Apparently the view from the top is amazing.", "도시에서 한 시간쯤 떨어진 등산로가 있어. 정상에서 보는 경치가 끝내준대."),
            ("Mike", M, "Nice, I could use some fresh air myself. Mind if I tag along?", "좋다, 나도 바람 좀 쐬어야 하는데. 나도 같이 가도 될까?"),
            ("Sarah", F, "Of course not, the more the merrier. We're meeting at the trailhead around eight.", "당연하지, 사람 많을수록 좋아. 등산로 입구에서 8시쯤 만나기로 했어."),
            ("Mike", M, "Eight in the morning? That's early.", "아침 8시? 이르다."),
            ("Sarah", F, "I know, but it gets pretty hot by noon, so we want to beat the heat.", "그러니까, 근데 정오쯤 되면 꽤 더워져서 더위 피하려고 그래."),
            ("Mike", M, "Fair enough. I'll set an alarm, then. Should I bring anything?", "그건 그렇네. 그럼 알람 맞춰놔야겠다. 뭐 챙겨갈 거 있어?"),
            ("Sarah", F, "Just bring plenty of water and maybe a snack. We're not stopping for lunch or anything.", "물 넉넉히 챙기고 간식 정도만. 점심 먹으러 따로 멈추거나 하진 않을 거야."),
            ("Mike", M, "Got it. I'll pack some trail mix and a couple of sandwiches.", "알겠어. 견과류 믹스랑 샌드위치 몇 개 챙겨갈게."),
            ("Sarah", F, "Perfect. Oh, and wear proper shoes. Last time someone showed up in sandals and really regretted it.", "완벽해. 아, 그리고 제대로 된 신발 신고 와. 지난번에 누가 샌들 신고 왔다가 완전 후회했거든."),
            ("Mike", M, "Noted. I will absolutely not be that guy.", "명심할게. 절대 그런 사람 되지 않을 거야."),
            ("Sarah", F, "Smart move. Anyway, how's your sister doing? Didn't she just move to a new apartment?", "현명하네. 그나저나 네 여동생은 잘 지내? 새 아파트로 막 이사하지 않았어?"),
            ("Mike", M, "Oh yeah, she just moved downtown a couple weeks ago. She loves it so far.", "아 맞아, 몇 주 전에 시내로 이사했어. 지금까지는 엄청 마음에 들어 해."),
            ("Sarah", F, "That's great. Is it close to her work?", "잘됐다. 회사랑 가까워?"),
            ("Mike", M, "Pretty close, actually. She can walk there in like fifteen minutes now.", "꽤 가까워. 이제 걸어서 15분 정도면 갈 수 있어."),
            ("Sarah", F, "Wow, that's such a relief compared to commuting, I bet.", "와, 예전 출퇴근에 비하면 완전 살겠다."),
            ("Mike", M, "Definitely. She used to spend almost an hour on the train every morning.", "그렇지. 예전엔 매일 아침 지하철에서 거의 한 시간씩 보냈거든."),
            ("Sarah", F, "I don't know how people do that every single day.", "사람들이 그걸 매일 어떻게 하는지 모르겠어."),
            ("Mike", M, "Right? Anyway, we should probably get going. I still need to grab groceries before everything closes.", "그니까. 아무튼 우리 이제 슬슬 가야 할 것 같아. 문 닫기 전에 장도 봐야 하고."),
            ("Sarah", F, "Oh, good call. I actually need to do the same thing.", "아, 그러네. 나도 사실 똑같이 해야 해."),
            ("Mike", M, "Great minds think alike. I'll see you Saturday at eight, then?", "역시 통하네. 그럼 토요일 8시에 보는 거지?"),
            ("Sarah", F, "Sounds good. Try not to be late this time!", "좋아. 이번엔 늦지 않도록 해!"),
            ("Mike", M, "No promises, but I'll try my best. Oh wait, actually, one more thing.", "장담은 못 하지만 노력해볼게. 아 잠깐, 하나 더 있다."),
            ("Sarah", F, "What's up?", "뭔데?"),
            ("Mike", M, "Is it okay if I bring my dog along? He's been cooped up inside all week.", "내 강아지도 데려가도 될까? 일주일 내내 집에만 갇혀 있었거든."),
            ("Sarah", F, "Oh, of course! Everyone loves Max. Just make sure to bring a leash and some water for him too.", "오, 당연하지! 다들 맥스 좋아하잖아. 목줄이랑 걔 마실 물도 꼭 챙겨와."),
            ("Mike", M, "Yeah, definitely. He gets pretty excited around other people, so I'll keep him close.", "응, 당연히. 다른 사람들 있으면 많이 흥분해서 가까이 붙여놓을게."),
            ("Sarah", F, "No worries, he's always been really well-behaved whenever I've seen him.", "걱정 마, 내가 볼 때마다 항상 얌전했어."),
            ("Mike", M, "That's good to hear. He can be a handful sometimes, especially around squirrels.", "다행이다. 가끔, 특히 다람쥐 보면 좀 감당이 안 될 때가 있거든."),
            ("Sarah", F, "Ha, that's pretty normal for dogs, though, right?", "하하, 근데 그건 강아지들한테 꽤 흔한 거 아니야?"),
            ("Mike", M, "True. Anyway, do you know if there's parking near the trailhead?", "맞아. 그나저나 등산로 입구 근처에 주차할 데 있는지 알아?"),
            ("Sarah", F, "There's a small lot, but it fills up fast on weekends, so we should probably carpool.", "작은 주차장이 있긴 한데, 주말엔 금방 차서 우리 같이 차 타고 가는 게 나을 것 같아."),
            ("Mike", M, "Good idea. Want me to pick you up on the way?", "좋은 생각이다. 가는 길에 내가 데리러 갈까?"),
            ("Sarah", F, "That would be great, actually. It'll save me from having to find parking myself.", "그럼 진짜 좋지. 나 혼자 주차 자리 찾을 필요 없어지니까."),
            ("Mike", M, "No problem. I'll swing by your place around seven thirty, then.", "문제없어. 그럼 7시 반쯤 너희 집에 들를게."),
            ("Sarah", F, "Perfect. I'll text you if anything changes with the plan.", "완벽해. 계획에 변동 있으면 문자할게."),
            ("Mike", M, "Sounds good. Oh, and one more thing, did you check the weather forecast?", "좋아. 아, 그리고 하나 더, 일기예보 확인해봤어?"),
            ("Sarah", F, "I did, actually. It looks mostly sunny, but there's a small chance of rain in the afternoon.", "응 확인했어. 대체로 맑을 것 같은데, 오후에 비 올 가능성이 조금 있대."),
            ("Mike", M, "Should be fine, then, since we'll be heading back before it gets bad.", "그럼 괜찮겠다, 어차피 날씨 나빠지기 전에 돌아올 거니까."),
            ("Sarah", F, "Yeah, exactly. Better bring a light jacket just in case, though.", "맞아, 그래도 혹시 모르니까 얇은 재킷 챙기는 게 좋겠어."),
            ("Mike", M, "Will do. Alright, I really should get going now before the store closes.", "그럴게. 자, 이제 진짜 가야겠다, 가게 문 닫기 전에."),
            ("Sarah", F, "Go, go! I'll talk to you later. Thanks for catching up with me.", "얼른 가! 나중에 또 얘기하자. 오랜만에 얘기 나눠서 좋았어."),
            ("Mike", M, "Of course, it was really great seeing you. Take care, Sarah!", "당연하지, 만나서 진짜 반가웠어. 잘 지내, 사라!"),
            ("Sarah", F, "You too, Mike. See you Saturday!", "너도, 마이크. 토요일에 보자!"),
        ],
    },
    {
        "id": "day02_coffee",
        "title": "Monday Morning Coffee Run",
        "topic": "월요일 아침, 카페에서 커피 주문하며 나누는 스몰토크",
        "dialogue": [
            ("Sarah", F, "Morning! You're here early today.", "좋은 아침! 오늘 일찍 왔네."),
            ("Mike", M, "Yeah, I couldn't really sleep, so I figured I'd just come in and get a head start.", "응, 잠이 잘 안 와서 그냥 일찍 나와서 미리 시작하려고."),
            ("Sarah", F, "Rough night?", "잠을 잘 못 잤어?"),
            ("Mike", M, "Kind of. My neighbors were having some kind of party until like two in the morning.", "그런 셈이지. 옆집에서 새벽 2시까지 무슨 파티를 하더라고."),
            ("Sarah", F, "Oh no, that's the worst. Did you say anything to them?", "이런, 최악이다. 뭐라고 말은 했어?"),
            ("Mike", M, "I thought about it, but by the time I got annoyed enough, it was already quiet again.", "생각은 했는데, 진짜 짜증 날 때쯤 되니까 벌써 조용해졌더라고."),
            ("Sarah", F, "Ha, typical. Well, you definitely need coffee, then.", "하하, 딱 그렇지. 그럼 오늘은 커피 필수네."),
            ("Mike", M, "Absolutely. I might need two, honestly.", "당연하지. 솔직히 두 잔은 필요할지도."),
            ("Sarah", F, "What are you getting?", "뭐 마실 거야?"),
            ("Mike", M, "Probably just a large black coffee. Nothing fancy, I just need the caffeine.", "그냥 큰 사이즈 블랙커피 마실 것 같아. 특별한 거 말고, 그냥 카페인이 필요해."),
            ("Sarah", F, "I'm feeling a little more adventurous. I think I'll get a caramel latte.", "나는 좀 더 색다른 거 마시고 싶어. 카라멜 라떼 마실까 해."),
            ("Mike", M, "Ooh, that sounds good, actually. Maybe I should switch my order.", "오, 그거 진짜 맛있겠다. 나도 주문 바꿀까."),
            ("Sarah", F, "You always say that and then you get plain black coffee anyway.", "너 항상 그렇게 말하고 결국 그냥 블랙커피 시키잖아."),
            ("Mike", M, "That's fair, that's fair. Old habits, I guess.", "그건 맞는 말이야. 그냥 습관인가 봐."),
            ("Sarah", F, "By the way, did you end up watching that show I told you about?", "그나저나 내가 얘기했던 그 드라마 봤어?"),
            ("Mike", M, "Oh, right, I actually started it this weekend. I'm already on episode five.", "아 맞다, 이번 주말에 사실 보기 시작했어. 벌써 5화까지 봤어."),
            ("Sarah", F, "No way, already? What do you think so far?", "진짜? 벌써? 지금까지 어때?"),
            ("Mike", M, "Honestly, it's really good. I wasn't expecting to get so hooked.", "솔직히 진짜 재밌어. 이렇게 빠져들 줄은 몰랐어."),
            ("Sarah", F, "I told you! Wait until you get to episode eight, though. That's when things get crazy.", "그러니까 내가 뭐랬어! 근데 8화까지 기다려봐. 거기서부터 완전 난리 나."),
            ("Mike", M, "Oh no, now I'm nervous. Should I be preparing myself emotionally?", "이런, 벌써 긴장되네. 마음의 준비를 해야 하는 거야?"),
            ("Sarah", F, "Honestly, yes. I actually gasped out loud when I watched it.", "솔직히, 응. 나는 볼 때 진짜 소리 내서 놀랐어."),
            ("Mike", M, "Great, thanks for the warning. Anyway, are you excited for the meeting today?", "잘됐네, 미리 알려줘서 고마워. 근데 오늘 회의 기대돼?"),
            ("Sarah", F, "Not really, if I'm being honest. I feel like it could've just been an email.", "솔직히 별로. 그냥 이메일로 해도 됐을 것 같은데."),
            ("Mike", M, "Ha, I feel that way about most meetings, to be honest.", "하하, 솔직히 대부분의 회의가 그런 것 같아."),
            ("Sarah", F, "Right? At least we'll have coffee in hand while we suffer through it.", "그니까? 그래도 커피는 손에 들고 버틸 수 있잖아."),
            ("Mike", M, "That's the spirit. Coffee makes everything a little more bearable.", "그런 자세지. 커피가 있으면 뭐든 좀 견딜 만해져."),
            ("Sarah", F, "By the way, do you have any plans for the weekend yet?", "그나저나 주말 계획은 아직 없어?"),
            ("Mike", M, "Not really, honestly. I might just catch up on sleep and do absolutely nothing.", "솔직히 딱히 없어. 그냥 밀린 잠 자면서 아무것도 안 할 것 같아."),
            ("Sarah", F, "Ha, that actually sounds kind of nice, though.", "하하, 근데 그것도 꽤 괜찮게 들린다."),
            ("Mike", M, "Right? Sometimes doing nothing is exactly what I need. What about you?", "그치? 가끔은 아무것도 안 하는 게 딱 필요할 때가 있어. 너는?"),
            ("Sarah", F, "There's actually a farmers market opening near my place this weekend. I want to check it out.", "사실 이번 주말에 우리 집 근처에 파머스 마켓이 새로 열려. 한번 가보려고."),
            ("Mike", M, "Oh, that sounds fun. What kind of stuff do they usually sell at those?", "오, 재밌겠다. 그런 데는 보통 뭘 파는데?"),
            ("Sarah", F, "Mostly local produce, but sometimes there's fresh bread and homemade jam, too.", "주로 지역 농산물인데, 가끔 갓 구운 빵이랑 수제 잼도 있어."),
            ("Mike", M, "Nice, that sounds way better than the grocery store, honestly.", "좋다, 솔직히 마트보다 훨씬 나을 것 같아."),
            ("Sarah", F, "Yeah, plus it's nice to actually get outside and walk around for once.", "응, 게다가 오랜만에 밖에 나가서 걸어 다니는 것도 좋고."),
            ("Mike", M, "That's true. I've honestly been stuck inside way too much lately.", "맞아. 나도 솔직히 요즘 집에만 너무 있었어."),
            ("Sarah", F, "You should come, then. It starts around nine, I think.", "그럼 같이 가자. 아마 9시쯤 시작할 거야."),
            ("Mike", M, "Nine might be a stretch after this week, but I'll see how I feel.", "이번 주 지나고 9시는 좀 힘들 수도 있는데, 그래도 컨디션 봐서 갈게."),
            ("Sarah", F, "Ha, fair enough. No pressure, just let me know.", "하하, 그건 그렇지. 부담 갖지 말고 그냥 알려줘."),
            ("Sarah", F, "Speaking of which, our order should be ready soon. It's usually pretty quick here.", "그 얘기가 나와서 말인데, 우리 주문 곧 나올 거야. 여기 보통 빨리 나오거든."),
            ("Mike", M, "Good, because I really need to sit down for a second before the meeting.", "다행이다, 회의 전에 진짜 잠깐 앉아 있어야 할 것 같아."),
            ("Sarah", F, "Same here. Oh, they just called our names, actually.", "나도 그래. 아, 방금 우리 이름 불렀다."),
            ("Mike", M, "Perfect timing. Oh, before I forget, did you want to split a muffin or something?", "타이밍 완벽하네. 아, 잊기 전에, 머핀 같은 거 나눠 먹을래?"),
            ("Sarah", F, "Actually, yeah, that sounds great. I skipped breakfast this morning.", "어, 그거 좋다. 오늘 아침 못 먹었거든."),
            ("Mike", M, "Same, honestly. I was running late and just grabbed my bag and left.", "나도 그래, 솔직히. 늦어서 그냥 가방만 들고 나왔어."),
            ("Sarah", F, "Classic Monday morning, right? Let's grab our drinks and head over.", "전형적인 월요일 아침이지, 그치? 음료 챙겨서 가자."),
            ("Sarah", F, "Sounds good. Thanks for keeping me company this morning.", "좋아. 오늘 아침에 같이 있어줘서 고마워."),
            ("Mike", M, "Anytime. Alright, let's go tackle this meeting.", "언제든지. 자, 이제 회의 시작하러 가자."),
            ("Sarah", F, "Let's do it. Wish us luck.", "가보자. 행운을 빌자."),
        ],
    },
    {
        "id": "day03_groceries",
        "title": "Grocery Store Run",
        "topic": "장 보다가 마주친 친구와 저녁 메뉴 얘기하기",
        "dialogue": [
            ("Mike", M, "Sarah? Oh wow, small world. Fancy seeing you here.", "사라? 오, 진짜 세상 좁다. 여기서 다 보네."),
            ("Sarah", F, "Mike! Hi! I didn't know you shopped at this place.", "마이크! 안녕! 네가 여기서 장 보는 줄 몰랐어."),
            ("Mike", M, "I usually don't, but the store near my place was out of basically everything.", "보통은 안 오는데, 우리 집 근처 마트에 물건이 거의 다 떨어졌더라고."),
            ("Sarah", F, "Oh, that's annoying. What are you shopping for today?", "아, 짜증 나겠다. 오늘 뭐 사러 왔어?"),
            ("Mike", M, "Honestly, I have no plan. I'm just wandering around hoping for inspiration.", "솔직히 계획이 없어. 그냥 돌아다니면서 아이디어 떠오르길 바라고 있어."),
            ("Sarah", F, "Ha, that's exactly what I do every single time.", "하하, 나도 매번 딱 그렇게 해."),
            ("Mike", M, "At least I'm not alone, then. What are you thinking of making tonight?", "그럼 나 혼자만 그런 건 아니네. 오늘 저녁엔 뭐 만들 생각이야?"),
            ("Sarah", F, "I was actually thinking about doing a stir fry. I have some vegetables that need to be used up.", "사실 볶음 요리 할까 생각 중이었어. 빨리 써야 하는 채소들이 좀 있거든."),
            ("Mike", M, "Oh, that sounds easy and pretty healthy, too.", "오, 그거 쉽고 건강해 보인다."),
            ("Sarah", F, "Yeah, plus it's a good way to clean out the fridge before it all goes bad.", "응, 게다가 냉장고 정리하기에도 좋고, 다 상하기 전에."),
            ("Mike", M, "Smart. I really need to start meal planning like that.", "똑똑하네. 나도 그렇게 식단 계획을 세워야 하는데."),
            ("Sarah", F, "Do you not usually plan your meals?", "평소엔 식단 계획 안 세워?"),
            ("Mike", M, "Not really. I basically decide what to eat about ten minutes before I'm hungry.", "별로. 배고프기 십 분 전쯤 돼서야 뭐 먹을지 결정해."),
            ("Sarah", F, "Ha, that explains why you're wandering around aimlessly, then.", "하하, 그래서 지금 목적 없이 돌아다니는 거구나."),
            ("Mike", M, "Exactly. Honestly, I might just grab some frozen dumplings and call it a night.", "정확해. 솔직히 그냥 냉동 만두 사서 저녁 때울 것 같아."),
            ("Sarah", F, "There's nothing wrong with that. Sometimes easy is best.", "그것도 나쁘지 않아. 가끔은 간단한 게 최고지."),
            ("Mike", M, "True. By the way, have prices gone up here, too? Everything feels more expensive lately.", "맞아. 근데 여기도 물가 오르지 않았어? 요즘 뭐든지 다 비싸진 느낌이야."),
            ("Sarah", F, "Oh, don't even get me started. I swear eggs cost double what they used to.", "아, 그 얘기 꺼내지도 마. 계란 값이 예전보다 두 배는 된 것 같아."),
            ("Mike", M, "Right? I almost dropped my basket when I saw the price of avocados earlier.", "그니까? 아까 아보카도 가격 보고 바구니 놓칠 뻔했어."),
            ("Sarah", F, "Avocados are basically a luxury item at this point.", "아보카도는 이제 거의 사치품 수준이야."),
            ("Mike", M, "Seriously. Anyway, have you tried cooking anything new lately?", "진짜야. 그나저나 요즘 새로운 요리 시도해본 거 있어?"),
            ("Sarah", F, "Actually, yeah. I tried making my own bread for the first time last week.", "어, 있어. 지난주에 처음으로 빵을 직접 만들어봤어."),
            ("Mike", M, "Whoa, that's impressive. How did it turn out?", "와, 대단하다. 어떻게 됐어?"),
            ("Sarah", F, "Surprisingly well, actually. It wasn't perfect, but it was definitely edible.", "의외로 잘 나왔어. 완벽하진 않았지만 확실히 먹을 만했어."),
            ("Mike", M, "That's more than I could say for my cooking attempts, honestly.", "솔직히 내 요리 시도보다는 훨씬 낫네."),
            ("Sarah", F, "Ha, it just took a lot of patience. The dough has to rise for hours.", "하하, 그냥 인내심이 많이 필요했어. 반죽이 몇 시간 동안 부풀어야 하거든."),
            ("Mike", M, "Hours? Yeah, that's not really my style. I get impatient after like ten minutes.", "몇 시간이라고? 그건 나랑 안 맞는 것 같아. 나는 10분만 지나도 못 참거든."),
            ("Sarah", F, "Ha, that's fair. Baking definitely isn't for everyone.", "하하, 그건 그렇지. 베이킹이 다 맞는 건 아니니까."),
            ("Mike", M, "Maybe I'll stick to reheating things in the microwave for now.", "나는 그냥 당분간 전자레인지에 데우는 걸로 만족해야겠다."),
            ("Sarah", F, "Ha, no judgment here. Sometimes that's exactly what you need.", "하하, 그것도 나쁘지 않아. 가끔은 그게 딱 필요할 때도 있으니까."),
            ("Mike", M, "Anyway, are you still coming to Jenny's birthday thing next week?", "아무튼, 다음 주 제니 생일 모임에 아직 갈 거야?"),
            ("Sarah", F, "Oh yeah, definitely. I still need to figure out what to get her, though.", "응, 당연히 가지. 근데 아직 뭘 선물할지 정해야 해."),
            ("Mike", M, "Same here. Any ideas so far?", "나도 그래. 지금까지 생각해둔 거 있어?"),
            ("Sarah", F, "Maybe something from that new bakery she keeps talking about. She's obsessed with it.", "걔가 요즘 계속 얘기하는 그 새 빵집 거 뭔가 사줄까 싶어. 완전 꽂혀 있더라고."),
            ("Mike", M, "Oh, that's actually a great idea. Way better than whatever I was going to get.", "오, 그거 진짜 좋은 생각이다. 내가 생각했던 것보다 훨씬 낫네."),
            ("Sarah", F, "What were you going to get?", "뭐 사주려고 했었는데?"),
            ("Mike", M, "Honestly, I hadn't thought that far. Probably a gift card, if I'm being lazy.", "솔직히 거기까진 생각 안 했어. 귀찮으면 그냥 상품권 살 것 같아."),
            ("Sarah", F, "Ha, classic Mike. Oh, one more thing, do you know if they have any good wine here?", "하하, 역시 마이크답다. 아, 하나 더, 여기 괜찮은 와인 있는지 알아?"),
            ("Mike", M, "Actually, yeah. There's a decent selection in the back corner, past the bread section.", "어, 있어. 빵 코너 지나서 뒤쪽 구석에 꽤 괜찮은 게 있어."),
            ("Sarah", F, "Oh, nice, I might grab a bottle for Jenny's party, then.", "오 좋다, 그럼 제니 파티에 가져갈 와인 한 병 사야겠다."),
            ("Mike", M, "Good call, that's probably safer than a gift card, honestly.", "좋은 생각이야, 솔직히 상품권보다 훨씬 나을 것 같아."),
            ("Sarah", F, "Ha, definitely. Alright, well, I should probably finish shopping before it gets too late.", "하하, 확실히 그렇지. 자, 나 너무 늦기 전에 장 봐야 할 것 같아."),
            ("Mike", M, "Yeah, me too. It was really nice running into you, though.", "응, 나도. 그래도 여기서 만나서 진짜 반가웠어."),
            ("Sarah", F, "You too! Let's grab lunch sometime this week if you're free.", "나도! 이번 주에 시간 되면 점심 같이 먹자."),
            ("Mike", M, "For sure, I'll text you. Enjoy your stir fry tonight.", "당연하지, 문자할게. 오늘 볶음 요리 맛있게 먹어."),
            ("Sarah", F, "Thanks, enjoy your frozen dumplings.", "고마워, 냉동 만두 맛있게 먹어."),
        ],
    },
    {
        "id": "day04_gym",
        "title": "Morning Gym Session",
        "topic": "헬스장에서 만나 새해 다짐과 운동 루틴 얘기하기",
        "dialogue": [
            ("Sarah", F, "Mike, hey! I didn't expect to see you here this early.", "마이크, 안녕! 이렇게 일찍 여기서 볼 줄은 몰랐어."),
            ("Mike", M, "Ha, I know, right? I'm actually trying to be more consistent this year.", "하하, 그니까 말이야. 올해는 좀 더 꾸준히 해보려고 노력 중이야."),
            ("Sarah", F, "That's the New Year's resolution, huh?", "그게 새해 다짐이구나, 그치?"),
            ("Mike", M, "Yeah, pretty much. Let's see how long it actually lasts, though.", "응, 대충 그래. 근데 이게 얼마나 갈지는 두고 봐야지."),
            ("Sarah", F, "Ha, don't worry, everyone says that. I'm on week three myself.", "하하, 걱정 마, 다들 그래. 나도 이제 3주째야."),
            ("Mike", M, "Oh, nice, that's actually pretty solid already.", "오, 좋다, 그 정도면 벌써 꽤 잘하고 있는 거네."),
            ("Sarah", F, "Thanks, I'm trying. What are you working on today?", "고마워, 노력 중이야. 오늘은 뭐 할 거야?"),
            ("Mike", M, "Mostly legs, I think. Although I'm already regretting that decision a little.", "주로 하체 할 것 같아. 근데 벌써 조금 후회되긴 해."),
            ("Sarah", F, "Ha, leg day will do that to you. I'm just doing some cardio today.", "하하, 하체 날은 원래 그래. 나는 오늘 그냥 유산소만 할 거야."),
            ("Mike", M, "Smart. My legs are still sore from Tuesday, if I'm being honest.", "똑똑하네. 사실 화요일부터 다리가 아직도 아파."),
            ("Sarah", F, "Ha, that's rough. Maybe you should stretch more.", "하하, 힘들겠다. 스트레칭을 좀 더 해야 할 것 같은데."),
            ("Mike", M, "Yeah, I know I should. I always skip it because I'm impatient.", "응, 해야 되는 거 알지. 근데 성격이 급해서 항상 건너뛰게 돼."),
            ("Sarah", F, "Same, honestly. I only started stretching properly after I pulled a muscle last year.", "솔직히 나도 그래. 작년에 근육 다치고 나서야 제대로 스트레칭하기 시작했어."),
            ("Mike", M, "Oh no, what happened?", "어머, 무슨 일이었는데?"),
            ("Sarah", F, "I jumped straight into a run without warming up and my calf just gave out.", "준비운동도 없이 바로 뛰다가 종아리가 그냥 나가버렸어."),
            ("Mike", M, "Ouch, that sounds painful. Lesson learned, I guess.", "아야, 아팠겠다. 그래도 교훈은 얻었네."),
            ("Sarah", F, "Definitely. By the way, have you been tracking your workouts with anything?", "그렇지. 근데 운동은 뭐로 기록하고 있어?"),
            ("Mike", M, "I downloaded this app a few weeks ago. It's honestly been really motivating.", "몇 주 전에 앱을 하나 다운받았어. 솔직히 진짜 동기부여가 많이 돼."),
            ("Sarah", F, "Oh really? What does it do exactly?", "어, 진짜? 정확히 뭘 해주는데?"),
            ("Mike", M, "It just tracks my sets and reps, and shows me progress over time.", "그냥 세트랑 횟수를 기록해주고, 시간에 따른 발전 정도를 보여줘."),
            ("Sarah", F, "That sounds really useful. I've just been guessing this whole time.", "진짜 유용하겠다. 나는 그동안 그냥 감으로 했거든."),
            ("Mike", M, "Ha, I used to do that too, but seeing the numbers actually go up keeps me coming back.", "하하, 나도 예전엔 그랬는데, 숫자가 올라가는 걸 보니까 계속 오게 되더라고."),
            ("Sarah", F, "I might have to download it, then. What's it called?", "그럼 나도 다운받아야겠다. 이름이 뭐야?"),
            ("Mike", M, "I'll send you the link later. It's free, at least for the basic version.", "이따 링크 보내줄게. 기본 버전은 무료야."),
            ("Sarah", F, "Perfect, thanks. I could use a little extra motivation these days.", "완벽해, 고마워. 요즘 동기부여가 좀 더 필요했거든."),
            ("Mike", M, "Same here, honestly. That's basically the only reason I still show up some days.", "솔직히 나도 그래. 어떤 날은 그거 때문에 겨우 나오기도 해."),
            ("Sarah", F, "Anyway, are you still doing that fitness class on Thursdays?", "아무튼, 목요일마다 하는 그 피트니스 수업은 아직 다녀?"),
            ("Mike", M, "Yeah, actually. It's tough, but I really enjoy it.", "응, 아직 다녀. 힘들긴 한데 진짜 재밌어."),
            ("Sarah", F, "I've been wanting to try it. Is it hard to keep up if you're not super fit?", "나도 한번 해보고 싶었어. 체력이 그렇게 좋지 않아도 따라갈 만해?"),
            ("Mike", M, "Honestly, everyone goes at their own pace. The instructor is really encouraging.", "솔직히 다들 자기 페이스대로 해. 강사님이 정말 잘 격려해줘."),
            ("Sarah", F, "Oh, that's good to hear. Maybe I'll join you this week, then.", "오, 다행이다. 그럼 이번 주에 나도 같이 가볼까."),
            ("Mike", M, "You definitely should. It's a lot more fun with a friend there, too.", "당연히 그래야지. 친구랑 같이 하면 훨씬 재밌기도 하고."),
            ("Sarah", F, "Deal. I'll message you before Thursday to confirm.", "좋아. 목요일 전에 확실히 하려고 문자할게."),
            ("Mike", M, "Sounds good. By the way, do you want to grab a smoothie after this?", "좋아. 근데 운동 끝나고 스무디 마실래?"),
            ("Sarah", F, "Oh, that sounds amazing right about now.", "오, 지금 딱 그거 마시고 싶었어."),
            ("Mike", M, "Great, there's actually a new place that just opened up down the street.", "잘됐다, 사실 바로 근처에 새로 생긴 곳이 있어."),
            ("Sarah", F, "Oh, I think I saw that. Doesn't it have a really long line, though?", "아, 나 그거 본 것 같아. 근데 거기 줄이 되게 길지 않아?"),
            ("Mike", M, "It did on opening day, but it's calmed down a lot since then.", "오픈 첫날엔 그랬는데, 그 이후로는 많이 잠잠해졌어."),
            ("Sarah", F, "Good, because I don't think I'll have the patience to wait after a workout.", "다행이다, 운동 끝나고는 기다릴 인내심이 없을 것 같거든."),
            ("Mike", M, "Ha, fair. Let's aim to get there before the lunch rush, then.", "하하, 그건 맞아. 그럼 점심 붐비기 전에 가는 걸로 하자."),
            ("Sarah", F, "Perfect, let's check it out after we're done here.", "좋아, 여기 끝나고 한번 가보자."),
            ("Mike", M, "Alright, I better get started on these legs before I lose motivation.", "좋아, 의지 사라지기 전에 다리 운동 시작해야겠다."),
            ("Sarah", F, "Ha, good luck with that. I'll see you at the smoothie place after.", "하하, 화이팅. 이따 스무디 가게에서 보자."),
            ("Mike", M, "See you then. Have a good workout!", "이따 보자. 운동 잘하고!"),
        ],
    },
    {
        "id": "day05_rainy_commute",
        "title": "Waiting Out the Rain",
        "topic": "갑자기 쏟아진 비를 피해 처마 밑에서 나누는 대화",
        "dialogue": [
            ("Sarah", F, "Oh my gosh, Mike, hi. I did not expect this rain at all today.", "어머, 마이크, 안녕. 오늘 이렇게 비 올 줄 진짜 몰랐어."),
            ("Mike", M, "Tell me about it. I checked the forecast this morning and it said sunny all day.", "그니까 말이야. 아침에 일기예보 봤는데 하루 종일 맑다고 했거든."),
            ("Sarah", F, "Same here. I don't even have an umbrella with me.", "나도 그래. 우산도 안 챙겼어."),
            ("Mike", M, "Me neither. I guess we're both stuck under this awning for now.", "나도 없어. 우리 둘 다 당분간 이 처마 밑에 갇혀 있어야겠다."),
            ("Sarah", F, "Ha, could be worse. At least there's a decent view from here.", "하하, 이 정도면 괜찮아. 그래도 여기서 보는 경치는 나쁘지 않네."),
            ("Mike", M, "True, true. So, where were you headed before this whole downpour started?", "그러네. 그래서 이 폭우 오기 전에 어디 가던 길이었어?"),
            ("Sarah", F, "I was just running to grab lunch. Guess that plan's on hold now.", "그냥 점심 사러 가던 길이었어. 이제 그 계획은 잠깐 보류네."),
            ("Mike", M, "Same, actually. I was starving, and now I'm just standing here getting hungrier.", "나도 사실 그래. 배고파 죽겠는데 여기 서서 점점 더 배고파지고 있어."),
            ("Sarah", F, "Ha, at least we can suffer together, then.", "하하, 그럼 같이 고생이라도 하자."),
            ("Mike", M, "Exactly. Misery loves company, right?", "정확해. 힘든 건 같이 있으면 좀 덜하잖아, 그치?"),
            ("Sarah", F, "So, do we make a run for it, or just wait this out?", "그럼 우리 그냥 뛰어갈까, 아니면 그냥 기다릴까?"),
            ("Mike", M, "Honestly, it looks pretty heavy right now. I vote we wait a few minutes.", "솔직히 지금 되게 세게 오는 것 같아. 나는 몇 분만 기다리자는 쪽이야."),
            ("Sarah", F, "Yeah, that's probably smart. I really don't want to show up to work soaked.", "응, 그게 나을 것 같아. 회사에 홀딱 젖은 채로 가고 싶진 않아."),
            ("Mike", M, "Ha, same. That's a hard look to explain in meetings.", "하하, 나도 그래. 회의에서 그거 설명하기 참 애매하지."),
            ("Sarah", F, "Right? 'Sorry I'm dripping, it's a whole thing.'", "맞지? '죄송해요, 물이 뚝뚝 떨어지네요, 사연이 좀 있어요' 이러면서."),
            ("Mike", M, "Ha, exactly. So how's your week going so far, by the way?", "하하, 딱 그거네. 근데 이번 주는 어떻게 지내고 있어?"),
            ("Sarah", F, "Pretty busy, honestly. I've had back-to-back meetings since Monday.", "솔직히 꽤 바빠. 월요일부터 회의가 계속 이어졌어."),
            ("Mike", M, "Oh, that sounds draining. Any of them actually useful?", "오, 진 빠지겠다. 그중에 실제로 도움 되는 거 있었어?"),
            ("Sarah", F, "A couple, honestly. Most of them could've been an email, though.", "솔직히 몇 개는 있었어. 근데 대부분은 그냥 이메일로 됐을 것 같아."),
            ("Mike", M, "Ha, that's basically every meeting ever.", "하하, 그건 거의 모든 회의가 다 그렇지."),
            ("Sarah", F, "Fair point. Oh, hey, did you end up finishing that report you were working on?", "그건 맞는 말이야. 아 맞다, 저번에 하던 그 보고서는 결국 다 끝냈어?"),
            ("Mike", M, "Finally, yeah. I finished it late last night, actually.", "드디어, 응. 사실 어젯밤 늦게 끝냈어."),
            ("Sarah", F, "Oh, good. That thing seemed like it was stressing you out for weeks.", "오, 다행이다. 그거 때문에 몇 주 동안 스트레스 받는 것 같더라."),
            ("Mike", M, "It really was. I'm just relieved it's finally off my plate.", "진짜 그랬어. 이제 손 떠나서 그냥 안심돼."),
            ("Sarah", F, "I bet. Did your manager end up liking it?", "그럴 만해. 매니저는 마음에 들어 했어?"),
            ("Mike", M, "So far, so good. I haven't gotten any angry emails yet, at least.", "지금까지는 괜찮아. 적어도 아직 화난 이메일은 안 왔어."),
            ("Sarah", F, "Ha, that's basically the best outcome you can hope for.", "하하, 그게 사실상 최선의 결과지."),
            ("Mike", M, "Exactly. Low expectations, fewer disappointments.", "정확해. 기대치를 낮추면 실망할 일도 적어지니까."),
            ("Sarah", F, "Ha, that's oddly good advice, actually.", "하하, 은근히 좋은 조언이네."),
            ("Mike", M, "I try. Anyway, looks like the rain's letting up a little.", "노력 중이야. 아무튼 비가 좀 약해지는 것 같아."),
            ("Mike", M, "Oh, you're right. Maybe we can make a run for it now.", "어, 그러네. 이제 뛰어가도 될 것 같아."),
            ("Sarah", F, "Should we just sprint to that sandwich place on the corner?", "그냥 저 모퉁이에 있는 샌드위치 가게까지 뛰어갈까?"),
            ("Mike", M, "Works for me. On three?", "좋아. 셋 세면 뛰는 거지?"),
            ("Sarah", F, "Wait, actually, is that an umbrella in your bag? I think I see one poking out.", "잠깐, 근데 그거 네 가방에 있는 우산 아니야? 하나 삐져나온 것 같은데."),
            ("Mike", M, "Oh my gosh, you're right. I totally forgot I had that in there.", "어머, 진짜네. 거기 있는 거 완전히 잊고 있었어."),
            ("Sarah", F, "Mike! We've been standing here this whole time for nothing!", "마이크! 우리 이 시간 내내 그냥 여기 서 있었던 거잖아!"),
            ("Mike", M, "In my defense, I genuinely forgot. It's pretty tiny, though, so it might not help much.", "변명하자면, 진짜로 까먹고 있었어. 근데 크기가 되게 작아서 별 도움 안 될 수도 있어."),
            ("Sarah", F, "Better late than never, I guess. Okay, let's squeeze under it and go. One, two, three!", "그래도 안 하는 것보단 낫지. 좋아, 그 밑으로 껴서 가보자. 하나, 둘, 셋!"),
            ("Mike", M, "Okay, that tiny umbrella did basically nothing. That was way wetter than I expected.", "그 작은 우산은 거의 도움이 안 됐네. 생각보다 훨씬 많이 젖었다."),
            ("Sarah", F, "Ha, at least we made it. Worth it for lunch, though.", "하하, 그래도 도착은 했잖아. 그래도 점심 먹을 가치는 있었어."),
            ("Mike", M, "Definitely. Alright, let's dry off and figure out what to order.", "그렇지. 좋아, 좀 말리고 뭐 시킬지 정하자."),
            ("Sarah", F, "Sounds good. Thanks for waiting out the rain with me.", "좋아. 비 그칠 때까지 같이 기다려줘서 고마워."),
            ("Mike", M, "Anytime. Beats standing there alone, honestly.", "언제든지. 솔직히 혼자 서 있는 것보다 훨씬 낫지."),
        ],
    },
]
